{'migrations': [[{'action': 'db__create_table',
                  'field_queries': 'date_created timestamp NOT NULL DEFAULT '
                                   'now(), content varchar(255) NOT NULL, id '
                                   'serial primary key NOT NULL UNIQUE, price '
                                   "decimal(10,2) NOT NULL DEFAULT '25', name "
                                   'varchar(50) NOT NULL, quantity integer '
                                   "NOT NULL DEFAULT '1'",
                  'table_name': 'library'}],
                [{'action': 'db__table_add_column',
                  'field_creation_string': 'author integer references Author '
                                           'NULL',
                  'table_name': 'library'}],
                [{'action': 'db__constrain_table',
                  'constrain': ' UNIQUE (name,content) ',
                  'table_name': 'library'}]],
 'state': {'fields': {'author': {'db_column': 'author',
                                 'default': None,
                                 'foreign_key': 'Author',
                                 'null': True,
                                 'unique': False},
                      'content': {'choices': {'hard cover': 'hard cover book',
                                              'paperback': 'paperback book'},
                                  'db_column': 'content',
                                  'default': None,
                                  'max_length': 255,
                                  'null': False,
                                  'unique': False},
                      'date_created': {'auto_now': True,
                                       'choices': None,
                                       'db_column': 'date_created',
                                       'default': None,
                                       'null': False,
                                       'strftime': 'date %Y-%m-%d',
                                       'unique': False},
                      'id': {'db_column': 'id', 'null': False, 'unique': True},
                      'name': {'choices': None,
                               'db_column': 'name',
                               'default': None,
                               'max_length': 50,
                               'null': False,
                               'unique': False},
                      'price': {'choices': None,
                                'db_column': 'price',
                                'decimal_places': 2,
                                'default': 25,
                                'max_digits': 10,
                                'null': False,
                                'unique': False},
                      'quantity': {'choices': None,
                                   'db_column': 'quantity',
                                   'default': 1,
                                   'null': False,
                                   'unique': False}},
           'meta': {}}}
